import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/pages/**/*.{js,ts,jsx,tsx,mdx}", "./src/components/**/*.{js,ts,jsx,tsx,mdx}", "./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f4",
        primary: "#06274d",
        "primary-container": "#223d64",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#adc7f7",
        "on-primary": "#ffffff",
        "on-primary-container": "#8ea8d6",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#2d476f",
        "inverse-primary": "#adc7f7",
        secondary: "#735c00",
        "secondary-container": "#fed65b",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        tertiary: "#322400",
        "tertiary-container": "#4d3900",
        "tertiary-fixed": "#ffdf99",
        "tertiary-fixed-dim": "#f3bf32",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#d09f05",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#5a4300",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#fbf9f4",
        "surface-bright": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-variant": "#e4e2dd",
        "surface-container": "#f0eee9",
        "surface-container-low": "#f5f3ee",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-tint": "#455f88",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#43474c",
        "on-background": "#1b1c19",
        outline: "#74777d",
        "outline-variant": "#c4c6cd",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        scrim: "#000000",
      },
      fontFamily: {
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "var(--font-body)", "system-ui", "sans-serif"],
        headline: ["var(--font-display)", "var(--font-body)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
